#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-grafana
SERVICE_NAME="grafana"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting Grafana $(grafana --version | head -n 1 | awk '{print $NF}')"
exec sudo -u grafana grafana \
                                server \
                                --homepath="${HOME_PATH}" \
                                --config="${CONFIG_PATH%/}/${CONFIG_FILE}" \
                                --packaging=docker \
                                "$@" \
                                cfg:default.log.mode="${LOG_TYPE,,}" \
                                cfg:default.paths.data="${DATA_PATH}" \
                                cfg:default.paths.logs="${LOG_PATH}" \
                                cfg:default.paths.plugins="${PLUGINS_PATH}" \
                                cfg:default.paths.provisioning="${PROVISIONING_PATH}"
