#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 20-grafana
SERVICE_NAME="grafana"

sanity_var APP_URL "Full address of application"
grafana_bootstrap_filesystem
grafana_configure_monitoring
grafana_install_plugins
grafana_configure_application
grafana_configure_storage_aws

liftoff
